### ISSUE TITLE
Getting a php syntax error in test/mock-tinypng-webservice/output.php

### ISSUE THREAD

**Issue by jerturowetz** [tinify/wordpress-plugin#11]
PHP Parse error:  syntax error, unexpected '[' in - on line 13

**Comment by rolftimmermans** [comment]
Hi! Thanks for reporting this issue.  This error appears to be an issue with an older version of PHP. `test/mock-tinypng-webservice/output.php` is a file that should only be used during integration tests. These tests are not designed to run in older PHP versions.

Note that the client itself works fine in PHP 5.3 and above, but the integration tests don't. Maybe you could share some more details of what you are trying to accomplish?

**Comment by bydbest** [comment]
@jerturowetz 
i think this png/jpg/image compressor is better way2enjoy.com/compress-png as it allows 50 files in one chance. plugin is not recommended as it will always keep your server loaded with excess load. i agree that it will automate the process but when you can do samething in 1 second through online without slowing down your website then i think that is the best. if you know any better then kindly share link.
Get rid of Plugin and make super fast website. It takes 1 second to just browse your all files.(yes all files as you wont need more than 50 files for any article) so just upload and get compressed file instantly and enjoy the fast website
way2enjoy.com/compress-png

**Comment by jerturowetz** [comment]
I'm unsure if this is still occurring as I switched my personal plugin deployment method but feel free to reopen the issue if you would like me to check for you.
