### ISSUE TITLE
Plugin installed as "wordpress-plugin"

### ISSUE THREAD

**Issue by leek** [tinify/wordpress-plugin#19]
When this plugin is installed via Composer, it is installed to `wp-content/plugins/wordpress-plugin` because of the repo name.

**Comment by michielverkoijen** [comment]
Hi leek thanks for your contribution, we have now changed the name in composer.json to `tinify/tiny-compress-images` so it installs in an identifiable folder and matches the name used on wordpress.org and wpackagist.org.
