### ISSUE TITLE
Option to bulk optimize images >=200px only

### ISSUE THREAD

**Issue by karan-mo** [tinify/wordpress-plugin#27]
Currently there is only one option i.e. to bulk optimize the image. Can we add configuration to add image resolution (i.e > =1200px) or size (i.e >= 200kb) condition on it?

**Comment by StevenVanBlijderveen** [comment]
Hi there, I see you already got an answer for this question here: https://wordpress.org/support/topic/add-config-to-bulk-optimize-image-if-resolution-1200px-or-size-200kb/
